// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: add_episode.sql

package database

import (
	"context"
)

const addEpisode = `-- name: AddEpisode :one
INSERT INTO episodes(
    episode_number,
    filepath,
    viewtime,
    runtime,
    watched,
    show_title,
    season_number         
)
VALUES (
    ?1,
    ?2,
    0.0,
    ?3,
    FALSE,
    ?4,
    ?5
)
RETURNING episode_number, filepath, viewtime, runtime, watched, show_title, season_number
`

type AddEpisodeParams struct {
	EpisodeNumber int64
	Filepath      string
	Runtime       float64
	ShowTitle     string
	SeasonNumber  int64
}

func (q *Queries) AddEpisode(ctx context.Context, arg AddEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, addEpisode,
		arg.EpisodeNumber,
		arg.Filepath,
		arg.Runtime,
		arg.ShowTitle,
		arg.SeasonNumber,
	)
	var i Episode
	err := row.Scan(
		&i.EpisodeNumber,
		&i.Filepath,
		&i.Viewtime,
		&i.Runtime,
		&i.Watched,
		&i.ShowTitle,
		&i.SeasonNumber,
	)
	return i, err
}
