// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: add_season.sql

package database

import (
	"context"
)

const addSeason = `-- name: AddSeason :one
INSERT INTO seasons(season_number, total_episodes, unwatched_episodes, finished, show_title)
VALUES (
    sql.arg(season_number),
    ?1,
    ?1,
    FALSE,
    ?2
)
RETURNING season_number, total_episodes, unwatched_episodes, finished, show_title
`

type AddSeasonParams struct {
	TotalEpisodes int64
	ShowTitle     string
}

func (q *Queries) AddSeason(ctx context.Context, arg AddSeasonParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, addSeason, arg.TotalEpisodes, arg.ShowTitle)
	var i Season
	err := row.Scan(
		&i.SeasonNumber,
		&i.TotalEpisodes,
		&i.UnwatchedEpisodes,
		&i.Finished,
		&i.ShowTitle,
	)
	return i, err
}
