// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_season.sql

package database

import (
	"context"
)

const deleteSeason = `-- name: DeleteSeason :exec
DELETE FROM seasons
WHERE
    show_title = ?1 AND
    season_number = ?2
`

type DeleteSeasonParams struct {
	ShowTitle    string
	SeasonNumber int64
}

func (q *Queries) DeleteSeason(ctx context.Context, arg DeleteSeasonParams) error {
	_, err := q.db.ExecContext(ctx, deleteSeason, arg.ShowTitle, arg.SeasonNumber)
	return err
}
