// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_episode.sql

package database

import (
	"context"
)

const deleteEpisode = `-- name: DeleteEpisode :exec
DELETE FROM episodes
WHERE
    show_title = ?1 AND
    season_number = ?2 AND
    episode_number = ?3
`

type DeleteEpisodeParams struct {
	ShowTitle     string
	SeasonNumber  int64
	EpisodeNumber int64
}

func (q *Queries) DeleteEpisode(ctx context.Context, arg DeleteEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, deleteEpisode, arg.ShowTitle, arg.SeasonNumber, arg.EpisodeNumber)
	return err
}
