// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_show.sql

package database

import (
	"context"
)

const deleteShow = `-- name: DeleteShow :exec
DELETE FROM shows
WHERE title = ?1
`

func (q *Queries) DeleteShow(ctx context.Context, showTitle string) error {
	_, err := q.db.ExecContext(ctx, deleteShow, showTitle)
	return err
}
