// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_next_unfinished_season.sql

package database

import (
	"context"
)

const getNextUnfinishedSeason = `-- name: GetNextUnfinishedSeason :one
SELECT season_number, total_episodes, unwatched_episodes, finished, show_title FROM seasons
WHERE
    finished = FALSE AND
    show_title = ?1
ORDER BY season_number ASC
LIMIT 1
`

func (q *Queries) GetNextUnfinishedSeason(ctx context.Context, showTitle string) (Season, error) {
	row := q.db.QueryRowContext(ctx, getNextUnfinishedSeason, showTitle)
	var i Season
	err := row.Scan(
		&i.SeasonNumber,
		&i.TotalEpisodes,
		&i.UnwatchedEpisodes,
		&i.Finished,
		&i.ShowTitle,
	)
	return i, err
}
