// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_no_progress_season_episodes.sql

package database

import (
	"context"
)

const getNoProgressSeasonEpisodes = `-- name: GetNoProgressSeasonEpisodes :many
SELECT episode_number, filepath, viewtime, runtime, watched, show_title, season_number FROM episodes
WHERE
    show_title = ?1 AND
    season_number = ?2 AND
    viewtime = 0.0
ORDER BY episode_number ASC
`

type GetNoProgressSeasonEpisodesParams struct {
	ShowTitle    string
	SeasonNumber int64
}

func (q *Queries) GetNoProgressSeasonEpisodes(ctx context.Context, arg GetNoProgressSeasonEpisodesParams) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, getNoProgressSeasonEpisodes, arg.ShowTitle, arg.SeasonNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.EpisodeNumber,
			&i.Filepath,
			&i.Viewtime,
			&i.Runtime,
			&i.Watched,
			&i.ShowTitle,
			&i.SeasonNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
