// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_next_no_progress_season_episode.sql

package database

import (
	"context"
)

const getNextNoProgressEpisodeFromSeason = `-- name: GetNextNoProgressEpisodeFromSeason :one
SELECT episode_number, filepath, viewtime, runtime, watched, show_title, season_number FROM episodes
WHERE
    show_title = ?1 AND
    season_number = ?2 AND
    viewtime = 0.0
ORDER BY episode_number ASC
LIMIT 1
`

type GetNextNoProgressEpisodeFromSeasonParams struct {
	ShowTitle    string
	SeasonNumber int64
}

func (q *Queries) GetNextNoProgressEpisodeFromSeason(ctx context.Context, arg GetNextNoProgressEpisodeFromSeasonParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getNextNoProgressEpisodeFromSeason, arg.ShowTitle, arg.SeasonNumber)
	var i Episode
	err := row.Scan(
		&i.EpisodeNumber,
		&i.Filepath,
		&i.Viewtime,
		&i.Runtime,
		&i.Watched,
		&i.ShowTitle,
		&i.SeasonNumber,
	)
	return i, err
}
