// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_all_shows.sql

package database

import (
	"context"
)

const getAllShows = `-- name: GetAllShows :many
SELECT id, title, seasons, total_episodes, unwatched_episodes FROM shows
`

func (q *Queries) GetAllShows(ctx context.Context) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getAllShows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Seasons,
			&i.TotalEpisodes,
			&i.UnwatchedEpisodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
