// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_next_unwatched_season_episode.sql

package database

import (
	"context"
)

const getNextUnwatchedSeasonEpisode = `-- name: GetNextUnwatchedSeasonEpisode :one
SELECT episode_number, filepath, viewtime, runtime, watched, show_title, season_number
FROM episodes
WHERE 
    watched = FALSE AND
    season_number = ?1 AND
    show_title = ?2
ORDER BY episode_number ASC
LIMIT 1
`

type GetNextUnwatchedSeasonEpisodeParams struct {
	SeasonNumber int64
	ShowTitle    string
}

func (q *Queries) GetNextUnwatchedSeasonEpisode(ctx context.Context, arg GetNextUnwatchedSeasonEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getNextUnwatchedSeasonEpisode, arg.SeasonNumber, arg.ShowTitle)
	var i Episode
	err := row.Scan(
		&i.EpisodeNumber,
		&i.Filepath,
		&i.Viewtime,
		&i.Runtime,
		&i.Watched,
		&i.ShowTitle,
		&i.SeasonNumber,
	)
	return i, err
}
