// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_show.sql

package database

import (
	"context"
)

const getShow = `-- name: GetShow :one
SELECT id, title, seasons, total_episodes, unwatched_episodes FROM shows
WHERE title = ?1
`

func (q *Queries) GetShow(ctx context.Context, showTitle string) (Show, error) {
	row := q.db.QueryRowContext(ctx, getShow, showTitle)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Seasons,
		&i.TotalEpisodes,
		&i.UnwatchedEpisodes,
	)
	return i, err
}
