// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_all_show_episodes.sql

package database

import (
	"context"
)

const getAllShowEpisodes = `-- name: GetAllShowEpisodes :many
SELECT episode_number, filepath, viewtime, runtime, watched, show_title, season_number FROM episodes
WHERE show_title = ?1
ORDER BY season_number ASC, episode_number ASC
`

func (q *Queries) GetAllShowEpisodes(ctx context.Context, showTitle string) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, getAllShowEpisodes, showTitle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.EpisodeNumber,
			&i.Filepath,
			&i.Viewtime,
			&i.Runtime,
			&i.Watched,
			&i.ShowTitle,
			&i.SeasonNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
