// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_least_viewed_season.sql

package database

import (
	"context"
)

const getLeastViewedSeason = `-- name: GetLeastViewedSeason :one
WITH ViewtimeTotals AS (
    SELECT show_title, season_number, SUM(viewtime) AS total_viewtime
    FROM episodes
    GROUP BY (show_title, season_number)
)
SELECT s.season_number, s.total_episodes, s.unwatched_episodes, s.finished, s.show_title
FROM seasons s
JOIN ViewtimeTotals ct ON (s.show_title, s.season_number) = (ct.show_title, season_number)
WHERE 
    ct.total_viewtime = (SELECT MIN(total_viewtime) FROM ViewtimeTotals) AND
    s.show_title = ?1
ORDER BY season_number ASC
LIMIT 1
`

func (q *Queries) GetLeastViewedSeason(ctx context.Context, showTitle string) (Season, error) {
	row := q.db.QueryRowContext(ctx, getLeastViewedSeason, showTitle)
	var i Season
	err := row.Scan(
		&i.SeasonNumber,
		&i.TotalEpisodes,
		&i.UnwatchedEpisodes,
		&i.Finished,
		&i.ShowTitle,
	)
	return i, err
}
