// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_season.sql

package database

import (
	"context"
)

const getSeason = `-- name: GetSeason :one
SELECT season_number, total_episodes, unwatched_episodes, finished, show_title FROM seasons
WHERE 
    show_title = ?1 AND
    season_number = ?2
`

type GetSeasonParams struct {
	ShowTitle    string
	SeasonNumber int64
}

func (q *Queries) GetSeason(ctx context.Context, arg GetSeasonParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, getSeason, arg.ShowTitle, arg.SeasonNumber)
	var i Season
	err := row.Scan(
		&i.SeasonNumber,
		&i.TotalEpisodes,
		&i.UnwatchedEpisodes,
		&i.Finished,
		&i.ShowTitle,
	)
	return i, err
}
