// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_unwatched_season_episodes.sql

package database

import (
	"context"
)

const getUnwatchedSeasonEpisodes = `-- name: GetUnwatchedSeasonEpisodes :many
SELECT episode_number, filepath, viewtime, runtime, watched, show_title, season_number FROM episodes
WHERE 
    watched = FALSE AND
    season_number = ?1 AND
    show_title = ?2
ORDER BY episode_number ASC
`

type GetUnwatchedSeasonEpisodesParams struct {
	SeasonNumber int64
	ShowTitle    string
}

func (q *Queries) GetUnwatchedSeasonEpisodes(ctx context.Context, arg GetUnwatchedSeasonEpisodesParams) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, getUnwatchedSeasonEpisodes, arg.SeasonNumber, arg.ShowTitle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.EpisodeNumber,
			&i.Filepath,
			&i.Viewtime,
			&i.Runtime,
			&i.Watched,
			&i.ShowTitle,
			&i.SeasonNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
