// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_episode.sql

package database

import (
	"context"
)

const getEpisode = `-- name: GetEpisode :one
SELECT episode_number, filepath, viewtime, runtime, watched, show_title, season_number FROM episodes
WHERE
    show_title = ?1 AND
    season_number = ?2 AND
    episode_number = ?3
`

type GetEpisodeParams struct {
	ShowTitle     string
	SeasonNumber  int64
	EpisodeNumber int64
}

func (q *Queries) GetEpisode(ctx context.Context, arg GetEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisode, arg.ShowTitle, arg.SeasonNumber, arg.EpisodeNumber)
	var i Episode
	err := row.Scan(
		&i.EpisodeNumber,
		&i.Filepath,
		&i.Viewtime,
		&i.Runtime,
		&i.Watched,
		&i.ShowTitle,
		&i.SeasonNumber,
	)
	return i, err
}
