// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_unfinished_seasons.sql

package database

import (
	"context"
)

const getUnfinishedSeasons = `-- name: GetUnfinishedSeasons :many
SELECT season_number, total_episodes, unwatched_episodes, finished, show_title FROM seasons
WHERE 
    finished = FALSE AND
    show_title = ?1
ORDER BY season_number ASC
`

func (q *Queries) GetUnfinishedSeasons(ctx context.Context, showTitle string) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, getUnfinishedSeasons, showTitle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.SeasonNumber,
			&i.TotalEpisodes,
			&i.UnwatchedEpisodes,
			&i.Finished,
			&i.ShowTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
