// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type Episode struct {
	EpisodeNumber int64
	Filepath      string
	Viewtime      float64
	Runtime       float64
	Watched       bool
	ShowTitle     string
	SeasonNumber  int64
}

type Season struct {
	SeasonNumber      int64
	TotalEpisodes     int64
	UnwatchedEpisodes int64
	Finished          bool
	ShowTitle         string
}

type Show struct {
	ID                int64
	Title             string
	Seasons           int64
	TotalEpisodes     int64
	UnwatchedEpisodes int64
}
