// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overwrite_episode.sql

package database

import (
	"context"
)

const overwriteEpisode = `-- name: OverwriteEpisode :one
UPDATE episodes
SET viewtime = 0,
    watched = FALSE,
    runtime = ?1,
    filepath = ?2
WHERE
    show_title = ?3 AND
    season_number = ?4 AND
    episode_number = ?5
RETURNING episode_number, filepath, viewtime, runtime, watched, show_title, season_number
`

type OverwriteEpisodeParams struct {
	Runtime       float64
	Filepath      string
	ShowTitle     string
	SeasonNumber  int64
	EpisodeNumber int64
}

func (q *Queries) OverwriteEpisode(ctx context.Context, arg OverwriteEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, overwriteEpisode,
		arg.Runtime,
		arg.Filepath,
		arg.ShowTitle,
		arg.SeasonNumber,
		arg.EpisodeNumber,
	)
	var i Episode
	err := row.Scan(
		&i.EpisodeNumber,
		&i.Filepath,
		&i.Viewtime,
		&i.Runtime,
		&i.Watched,
		&i.ShowTitle,
		&i.SeasonNumber,
	)
	return i, err
}
