// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remove_season.sql

package database

import (
	"context"
)

const removeSeason = `-- name: RemoveSeason :exec
DELETE FROM seasons
WHERE
    show_title = ?1 AND
    season_number = ?2
`

type RemoveSeasonParams struct {
	ShowTitle    string
	SeasonNumber int64
}

func (q *Queries) RemoveSeason(ctx context.Context, arg RemoveSeasonParams) error {
	_, err := q.db.ExecContext(ctx, removeSeason, arg.ShowTitle, arg.SeasonNumber)
	return err
}
