// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remove_episode.sql

package database

import (
	"context"
)

const removeEpisode = `-- name: RemoveEpisode :exec
DELETE FROM episodes
WHERE
    show_title = ?1 AND
    season_number = ?2 AND
    episode_number = ?3
`

type RemoveEpisodeParams struct {
	ShowTitle     string
	SeasonNumber  int64
	EpisodeNumber int64
}

func (q *Queries) RemoveEpisode(ctx context.Context, arg RemoveEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, removeEpisode, arg.ShowTitle, arg.SeasonNumber, arg.EpisodeNumber)
	return err
}
