// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remove_show.sql

package database

import (
	"context"
)

const removeShow = `-- name: RemoveShow :exec
DELETE FROM shows
WHERE title = ?1
`

func (q *Queries) RemoveShow(ctx context.Context, showTitle string) error {
	_, err := q.db.ExecContext(ctx, removeShow, showTitle)
	return err
}
