// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset_episode_stats.sql

package database

import (
	"context"
)

const resetEpisodeStats = `-- name: ResetEpisodeStats :exec
UPDATE episodes
SET viewtime = 0.0,
    watched = FALSE
WHERE
    show_title = ?1 AND
    season_number = ?2 AND
    episode_number = ?3
`

type ResetEpisodeStatsParams struct {
	ShowTitle     string
	SeasonNumber  int64
	EpisodeNumber int64
}

func (q *Queries) ResetEpisodeStats(ctx context.Context, arg ResetEpisodeStatsParams) error {
	_, err := q.db.ExecContext(ctx, resetEpisodeStats, arg.ShowTitle, arg.SeasonNumber, arg.EpisodeNumber)
	return err
}
