// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset_episode_viewtime.sql

package database

import (
	"context"
)

const resetEpisodeViewtime = `-- name: ResetEpisodeViewtime :exec
UPDATE episodes
SET viewtime = 0.0,
    watched = FALSE
WHERE
    show_title = ?1 AND
    season_number = ?2 AND
    episode_number = ?3
`

type ResetEpisodeViewtimeParams struct {
	ShowTitle     string
	SeasonNumber  int64
	EpisodeNumber int64
}

func (q *Queries) ResetEpisodeViewtime(ctx context.Context, arg ResetEpisodeViewtimeParams) error {
	_, err := q.db.ExecContext(ctx, resetEpisodeViewtime, arg.ShowTitle, arg.SeasonNumber, arg.EpisodeNumber)
	return err
}
