// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset_show_stats.sql

package database

import (
	"context"
)

const resetShowStats = `-- name: ResetShowStats :exec
UPDATE episodes
SET viewtime = 0.0,
    watched = FALSE
WHERE show_title = ?1
`

func (q *Queries) ResetShowStats(ctx context.Context, showTitle string) error {
	_, err := q.db.ExecContext(ctx, resetShowStats, showTitle)
	return err
}
