// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: set_episodes_watched.sql

package database

import (
	"context"
)

const setEpisodesWatched = `-- name: SetEpisodesWatched :exec
UPDATE episodes
SET watched = TRUE,
    viewtime = runtime
WHERE
    show_title = ?1 AND
    season_number = ?2 AND
    ?3 <= episode_number AND
    episode_number <= ?4
`

type SetEpisodesWatchedParams struct {
	ShowTitle    string
	SeasonNumber int64
	RangeStart   int64
	RangeEnd     int64
}

func (q *Queries) SetEpisodesWatched(ctx context.Context, arg SetEpisodesWatchedParams) error {
	_, err := q.db.ExecContext(ctx, setEpisodesWatched,
		arg.ShowTitle,
		arg.SeasonNumber,
		arg.RangeStart,
		arg.RangeEnd,
	)
	return err
}
