// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: set_episode_range_unwatched.sql

package database

import (
	"context"
)

const setEpisodeRangeUnwatched = `-- name: SetEpisodeRangeUnwatched :exec
UPDATE episodes
SET watched = FALSE,
    viewtime = 0.0
WHERE
    show_title = ?1 AND
    season_number = ?2 AND
    ?3 <= episode_number AND
    episode_number <= ?4
`

type SetEpisodeRangeUnwatchedParams struct {
	ShowTitle    string
	SeasonNumber int64
	RangeStart   int64
	RangeEnd     int64
}

func (q *Queries) SetEpisodeRangeUnwatched(ctx context.Context, arg SetEpisodeRangeUnwatchedParams) error {
	_, err := q.db.ExecContext(ctx, setEpisodeRangeUnwatched,
		arg.ShowTitle,
		arg.SeasonNumber,
		arg.RangeStart,
		arg.RangeEnd,
	)
	return err
}
