// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: set_season_watched.sql

package database

import (
	"context"
)

const setEpisodesForSeasonWatched = `-- name: SetEpisodesForSeasonWatched :exec

UPDATE episodes
SET
    watched = TRUE,
    viewtime = runtime
WHERE
    show_title = ?1 AND
    season_number = ?2
`

type SetEpisodesForSeasonWatchedParams struct {
	ShowTitle    string
	SeasonNumber int64
}

func (q *Queries) SetEpisodesForSeasonWatched(ctx context.Context, arg SetEpisodesForSeasonWatchedParams) error {
	_, err := q.db.ExecContext(ctx, setEpisodesForSeasonWatched, arg.ShowTitle, arg.SeasonNumber)
	return err
}

const setSeasonFinished = `-- name: SetSeasonFinished :exec
UPDATE seasons
SET finished = TRUE
WHERE
    show_title = ?1 AND
    season_number = ?2
`

type SetSeasonFinishedParams struct {
	ShowTitle    string
	SeasonNumber int64
}

func (q *Queries) SetSeasonFinished(ctx context.Context, arg SetSeasonFinishedParams) error {
	_, err := q.db.ExecContext(ctx, setSeasonFinished, arg.ShowTitle, arg.SeasonNumber)
	return err
}
