// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: set_episode_watched.sql

package database

import (
	"context"
)

const setEpisodeWatched = `-- name: SetEpisodeWatched :exec
UPDATE episodes
SET watched = TRUE,
    viewtime = runtime
WHERE
    show_title = ?1 AND
    season_number = ?2 AND
    episode_number = ?3
`

type SetEpisodeWatchedParams struct {
	ShowTitle     string
	SeasonNumber  int64
	EpisodeNumber int64
}

func (q *Queries) SetEpisodeWatched(ctx context.Context, arg SetEpisodeWatchedParams) error {
	_, err := q.db.ExecContext(ctx, setEpisodeWatched, arg.ShowTitle, arg.SeasonNumber, arg.EpisodeNumber)
	return err
}
