// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_season.sql

package database

import (
	"context"
)

const updateSeason = `-- name: UpdateSeason :one
UPDATE seasons
SET
    unwatched_episodes = ?1,
    finished = ?2,
    total_episodes = ?3
WHERE
    show_title = ?4 AND
    season_number = ?5
RETURNING season_number, total_episodes, unwatched_episodes, finished, show_title
`

type UpdateSeasonParams struct {
	UnwatchedEpisodes int64
	Finished          bool
	TotalEpisodes     int64
	ShowTitle         string
	SeasonNumber      int64
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, updateSeason,
		arg.UnwatchedEpisodes,
		arg.Finished,
		arg.TotalEpisodes,
		arg.ShowTitle,
		arg.SeasonNumber,
	)
	var i Season
	err := row.Scan(
		&i.SeasonNumber,
		&i.TotalEpisodes,
		&i.UnwatchedEpisodes,
		&i.Finished,
		&i.ShowTitle,
	)
	return i, err
}
