// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_episode_filepath.sql

package database

import (
	"context"
)

const updateEpisodePath = `-- name: UpdateEpisodePath :exec
UPDATE episodes
SET filepath = ?1
WHERE
    show_title = ?2 AND
    season_number = ?3 AND
    episode_number = ?4
RETURNING episode_number, filepath, viewtime, runtime, watched, show_title, season_number
`

type UpdateEpisodePathParams struct {
	Filepath      string
	ShowTitle     string
	SeasonNumber  int64
	EpisodeNumber int64
}

func (q *Queries) UpdateEpisodePath(ctx context.Context, arg UpdateEpisodePathParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodePath,
		arg.Filepath,
		arg.ShowTitle,
		arg.SeasonNumber,
		arg.EpisodeNumber,
	)
	return err
}
