// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_show.sql

package database

import (
	"context"
)

const updateShow = `-- name: UpdateShow :one
UPDATE shows
SET
    unwatched_episodes = ?1,
    total_episodes = ?2,
    seasons = ?3
WHERE
    title = ?4
RETURNING id, title, seasons, total_episodes, unwatched_episodes
`

type UpdateShowParams struct {
	UnwatchedEpisodes int64
	TotalEpisodes     int64
	Seasons           int64
	ShowTitle         string
}

func (q *Queries) UpdateShow(ctx context.Context, arg UpdateShowParams) (Show, error) {
	row := q.db.QueryRowContext(ctx, updateShow,
		arg.UnwatchedEpisodes,
		arg.TotalEpisodes,
		arg.Seasons,
		arg.ShowTitle,
	)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Seasons,
		&i.TotalEpisodes,
		&i.UnwatchedEpisodes,
	)
	return i, err
}
