// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_episode_viewtime.sql

package database

import (
	"context"
)

const updateViewTime = `-- name: UpdateViewTime :one
UPDATE episodes
SET viewtime = ?1,
    watched = ?2
WHERE
    show_title = ?3 AND
    season_number = ?4 AND
    episode_number = ?5
RETURNING episode_number, filepath, viewtime, runtime, watched, show_title, season_number
`

type UpdateViewTimeParams struct {
	Viewtime      float64
	Watched       bool
	ShowTitle     string
	SeasonNumber  int64
	EpisodeNumber int64
}

func (q *Queries) UpdateViewTime(ctx context.Context, arg UpdateViewTimeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, updateViewTime,
		arg.Viewtime,
		arg.Watched,
		arg.ShowTitle,
		arg.SeasonNumber,
		arg.EpisodeNumber,
	)
	var i Episode
	err := row.Scan(
		&i.EpisodeNumber,
		&i.Filepath,
		&i.Viewtime,
		&i.Runtime,
		&i.Watched,
		&i.ShowTitle,
		&i.SeasonNumber,
	)
	return i, err
}
