// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wipe_database.sql

package database

import (
	"context"
)

const wipeDatabase = `-- name: WipeDatabase :exec
DELETE FROM shows
`

func (q *Queries) WipeDatabase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, wipeDatabase)
	return err
}
